In [4]:
##import the data from the files

import os
from os import path
import pandas as pd
import numpy as np
import pickle
from pandas_profiling import ProfileReport
from sklearn.model_selection import train_test_split


In [8]:
path = "F:/"

S1_Dataset_Path = os.path.join(path, "Assignments", "S1_Dataset" )
S2_Dataset_Path = os.path.join(path, "Assignments", "S2_Dataset")



In [9]:


path = "F:/"

## Define the values for gender
## Male = 0 and Female = 1 . Gender needs to be added in the last column.



S1_Dataset_Path = os.path.join(path, "Assignments", "S1_Dataset" )
S2_Dataset_Path = os.path.join(path, "Assignments", "S2_Dataset")

s1_data = pd.DataFrame()

for dataset in [S1_Dataset_Path]:
    for dataset in [S2_Dataset_Path]:
        data_path = os.path.join(path,dataset)

for filename in os.listdir(data_path):
       if filename != "README.txt" : 
            file_path = os.path.join(data_path,filename)
        
       ## if filename[-1] == 'F':
         ##   gender = 1
            
        ## else:
           ## gender = 0
            
data = pd.read_csv(file_path, header=None)
s1_data = s1_data.append(data, ignore_index=True)
        
        
  
    
s1_data.columns = ['Time', 'Frontal_Acc', 'Vertical_Acc', 'Lateral_Acc', 'ID', 'RSSI', 'Phase', ' Frequency', 'Activity' ]

print("Updated successfully!!! Done!!")

s1_data.info()

Updated successfully!!! Done!!
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Time          178 non-null    float64
 1   Frontal_Acc   178 non-null    float64
 2   Vertical_Acc  178 non-null    float64
 3   Lateral_Acc   178 non-null    float64
 4   ID            178 non-null    int64  
 5   RSSI          178 non-null    float64
 6   Phase         178 non-null    float64
 7    Frequency    178 non-null    float64
 8   Activity      178 non-null    int64  
dtypes: float64(7), int64(2)
memory usage: 12.6 KB


In [10]:
s1_data

Time  Frontal_Acc  Vertical_Acc  Lateral_Acc  ID  RSSI   Phase  \
0      0.00      0.11960       0.93932     0.043332   3 -61.0  5.3014   
1      2.75      0.41273       1.01970    -0.025087   3 -66.0  0.8805   
2      3.00      0.41273       1.01970    -0.025087   2 -59.5  4.4455   
3      3.50      0.52999       0.90487    -0.047893   3 -59.5  5.8583   
4      4.00      0.56517       0.74411    -0.447000   3 -61.5  5.4886   
..      ...          ...           ...          ...  ..   ...     ...   
173  444.00      0.90520       0.64076    -0.082102   1 -59.5  1.9574   
174  449.00      0.90520       0.64076    -0.082102   1 -59.0  6.2540   
175  451.50      0.42446       0.91636    -0.161920   1 -53.0  5.7156   
176  451.58      0.42446       0.91636    -0.161920   1 -52.0  5.8982   
177  452.25      0.58862       0.87042    -0.082102   1 -60.0  5.7033   

      Frequency  Activity  
0        922.25         1  
1        922.75         1  
2        923.75         1  
3        921.75         1  
4        923.25         1  
..          ...       ...  
173      922.25         2  
174      922.25         2  
175      922.25         4  
176      922.25         4  
177      925.75         4  

[178 rows x 9 columns]

In [11]:
## Dumping the raw data in the pickle. Dump to save it in the binary format

with open("data_format", 'wb') as pickle_file:
     pickle.dump(s1_data, pickle_file)
    



In [12]:

## The dataframe needs to be coverted to csv

data_csv = s1_data.to_csv("filename.csv", index=False)

In [13]:

## The csv now has to be read as a Dataframe so we simply convert it to the DataFrame
df = pd.read_csv("filename.csv")

In [14]:
df

Time  Frontal_Acc  Vertical_Acc  Lateral_Acc  ID  RSSI   Phase  \
0      0.00      0.11960       0.93932     0.043332   3 -61.0  5.3014   
1      2.75      0.41273       1.01970    -0.025087   3 -66.0  0.8805   
2      3.00      0.41273       1.01970    -0.025087   2 -59.5  4.4455   
3      3.50      0.52999       0.90487    -0.047893   3 -59.5  5.8583   
4      4.00      0.56517       0.74411    -0.447000   3 -61.5  5.4886   
..      ...          ...           ...          ...  ..   ...     ...   
173  444.00      0.90520       0.64076    -0.082102   1 -59.5  1.9574   
174  449.00      0.90520       0.64076    -0.082102   1 -59.0  6.2540   
175  451.50      0.42446       0.91636    -0.161920   1 -53.0  5.7156   
176  451.58      0.42446       0.91636    -0.161920   1 -52.0  5.8982   
177  452.25      0.58862       0.87042    -0.082102   1 -60.0  5.7033   

      Frequency  Activity  
0        922.25         1  
1        922.75         1  
2        923.75         1  
3        921.75         1  
4        923.25         1  
..          ...       ...  
173      922.25         2  
174      922.25         2  
175      922.25         4  
176      922.25         4  
177      925.75         4  

[178 rows x 9 columns]

In [15]:
## Once the dataframe is completed we can move on to DataProfiling

new_profile = ProfileReport(df)
new_profile.to_file("Analysis_Report.html")

## The features are not highly coorelated as per the data.

In [16]:
## Remove all the duplicated rows

df.drop_duplicates()

Time  Frontal_Acc  Vertical_Acc  Lateral_Acc  ID  RSSI   Phase  \
0      0.00      0.11960       0.93932     0.043332   3 -61.0  5.3014   
1      2.75      0.41273       1.01970    -0.025087   3 -66.0  0.8805   
2      3.00      0.41273       1.01970    -0.025087   2 -59.5  4.4455   
3      3.50      0.52999       0.90487    -0.047893   3 -59.5  5.8583   
4      4.00      0.56517       0.74411    -0.447000   3 -61.5  5.4886   
..      ...          ...           ...          ...  ..   ...     ...   
173  444.00      0.90520       0.64076    -0.082102   1 -59.5  1.9574   
174  449.00      0.90520       0.64076    -0.082102   1 -59.0  6.2540   
175  451.50      0.42446       0.91636    -0.161920   1 -53.0  5.7156   
176  451.58      0.42446       0.91636    -0.161920   1 -52.0  5.8982   
177  452.25      0.58862       0.87042    -0.082102   1 -60.0  5.7033   

      Frequency  Activity  
0        922.25         1  
1        922.75         1  
2        923.75         1  
3        921.75         1  
4        923.25         1  
..          ...       ...  
173      922.25         2  
174      922.25         2  
175      922.25         4  
176      922.25         4  
177      925.75         4  

[178 rows x 9 columns]

In [12]:
df.dropna(axis='columns')

Time  Frontal_Acc  Vertical_Acc  Lateral_Acc  ID  RSSI   Phase  \
0      0.00      0.11960       0.93932     0.043332   3 -61.0  5.3014   
1      2.75      0.41273       1.01970    -0.025087   3 -66.0  0.8805   
2      3.00      0.41273       1.01970    -0.025087   2 -59.5  4.4455   
3      3.50      0.52999       0.90487    -0.047893   3 -59.5  5.8583   
4      4.00      0.56517       0.74411    -0.447000   3 -61.5  5.4886   
..      ...          ...           ...          ...  ..   ...     ...   
173  444.00      0.90520       0.64076    -0.082102   1 -59.5  1.9574   
174  449.00      0.90520       0.64076    -0.082102   1 -59.0  6.2540   
175  451.50      0.42446       0.91636    -0.161920   1 -53.0  5.7156   
176  451.58      0.42446       0.91636    -0.161920   1 -52.0  5.8982   
177  452.25      0.58862       0.87042    -0.082102   1 -60.0  5.7033   

      Frequency  Activity  
0        922.25         1  
1        922.75         1  
2        923.75         1  
3        921.75         1  
4        923.25         1  
..          ...       ...  
173      922.25         2  
174      922.25         2  
175      922.25         4  
176      922.25         4  
177      925.75         4  

[178 rows x 9 columns]

In [13]:
df.Activity.value_counts()

2    77
1    42
4    39
3    20
Name: Activity, dtype: int64

In [14]:
df.head()

Time  Frontal_Acc  Vertical_Acc  Lateral_Acc  ID  RSSI   Phase   Frequency  \
0  0.00      0.11960       0.93932     0.043332   3 -61.0  5.3014      922.25   
1  2.75      0.41273       1.01970    -0.025087   3 -66.0  0.8805      922.75   
2  3.00      0.41273       1.01970    -0.025087   2 -59.5  4.4455      923.75   
3  3.50      0.52999       0.90487    -0.047893   3 -59.5  5.8583      921.75   
4  4.00      0.56517       0.74411    -0.447000   3 -61.5  5.4886      923.25   

   Activity  
0         1  
1         1  
2         1  
3         1  
4         1

In [15]:
df["Activity"].unique()

array([1, 3, 4, 2], dtype=int64)

In [16]:
from sklearn.preprocessing import LabelEncoder

activity_encoder = LabelEncoder()

In [17]:
activity_encoder.fit(df["Activity"])

LabelEncoder()

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Time          178 non-null    float64
 1   Frontal_Acc   178 non-null    float64
 2   Vertical_Acc  178 non-null    float64
 3   Lateral_Acc   178 non-null    float64
 4   ID            178 non-null    int64  
 5   RSSI          178 non-null    float64
 6   Phase         178 non-null    float64
 7    Frequency    178 non-null    float64
 8   Activity      178 non-null    int64  
dtypes: float64(7), int64(2)
memory usage: 12.6 KB


In [40]:
df["Activity"].value_counts()

2    77
1    42
4    39
3    20
Name: Activity, dtype: int64

In [41]:
df.isnull().sum()

Time            0
Frontal_Acc     0
Vertical_Acc    0
Lateral_Acc     0
ID              0
RSSI            0
Phase           0
 Frequency      0
Activity        0
dtype: int64

In [42]:
df.notnull().sum()

Time            178
Frontal_Acc     178
Vertical_Acc    178
Lateral_Acc     178
ID              178
RSSI            178
Phase           178
 Frequency      178
Activity        178
dtype: int64

In [44]:
df.columns

Index(['Time', 'Frontal_Acc', 'Vertical_Acc', 'Lateral_Acc', 'ID', 'RSSI',
       'Phase', ' Frequency', 'Activity'],
      dtype='object')

In [53]:
df[' Frequency'].unique()

array([922.25, 922.75, 923.75, 921.75, 923.25, 924.25, 921.25, 920.75,
       925.25, 920.25, 924.75, 925.75])

In [56]:
df['Time'].unique()

array([  0.   ,   2.75 ,   3.   ,   3.5  ,   4.   ,   4.75 ,   5.   ,
         5.25 ,   5.3  ,   5.5  ,   5.575,   5.6  ,   5.75 ,   5.825,
         6.   ,   6.25 ,   6.325,   6.5  ,   6.575,   6.75 ,   6.85 ,
         7.   ,   7.25 ,   7.5  ,   7.75 , 111.75 , 112.5  , 112.75 ,
       113.   , 114.25 , 114.75 , 115.   , 115.25 , 115.5  , 116.25 ,
       116.75 , 117.25 , 118.   , 118.25 , 119.75 , 120.5  , 121.25 ,
       121.75 , 122.25 , 124.75 , 124.83 , 126.   , 127.5  , 130.25 ,
       134.25 , 140.25 , 150.5  , 157.25 , 158.5  , 161.   , 162.5  ,
       163.75 , 166.75 , 168.75 , 175.75 , 176.75 , 178.5  , 179.75 ,
       181.   , 181.75 , 183.25 , 186.25 , 188.25 , 188.75 , 191.75 ,
       193.25 , 196.75 , 202.75 , 204.   , 205.5  , 208.   , 210.   ,
       210.75 , 212.5  , 215.   , 217.25 , 219.75 , 220.75 , 222.25 ,
       227.75 , 229.5  , 230.25 , 232.   , 236.75 , 239.   , 239.75 ,
       242.28 , 246.53 , 250.25 , 250.33 , 251.5  , 252.25 , 254.5  ,
       256.75 , 258.

In [59]:
df['Frontal_Acc'].unique()

array([ 0.1196   ,  0.41273  ,  0.52999  ,  0.56517  ,  0.31893  ,
        0.13132  ,  0.15478  ,  0.23685  ,  0.45964  ,  0.44791  ,
        0.70587  ,  0.42446  ,  0.17823  ,  0.50654  ,  0.47136  ,
       -0.0093803,  0.20168  ,  0.49481  ,  0.38928  ,  0.30721  ,
        0.91693  ,  0.84658  ,  0.96383  ,  0.77622  ,  0.79967  ,
        0.83485  ,  0.88175  ,  0.9052   ,  0.99901  ,  0.8114   ,
        0.82312  ,  0.89348  ,  0.7645   ,  0.7176   ,  0.27203  ,
        0.61207  ,  0.51826  ,  0.29548  ,  0.1665   ,  0.63552  ,
        0.28376  ,  0.40101  ,  0.14305  ,  0.0023451, -0.20871  ,
        0.35411  ,  0.18995  ,  0.60034  ,  0.54171  ,  0.2603   ,
        0.48309  ,  1.128    ,  1.0811   ,  0.97555  ,  0.58862  ])

In [60]:
df['Vertical_Acc'].unique()

array([0.93932, 1.0197 , 0.90487, 0.74411, 0.44555, 0.49148, 0.42258,
       0.37665, 0.38813, 0.3422 , 0.29627, 0.26182, 0.19292, 0.85894,
       0.99674, 0.92784, 1.0656 , 0.89339, 0.88191, 0.95081, 0.70966,
       1.0771 , 1.0082 , 0.68669, 0.72114, 0.67521, 0.75559, 0.69818,
       0.73263, 0.76708, 0.79004, 0.87042, 0.84746, 0.83597, 0.97377,
       0.82449, 0.45703, 0.31923, 0.2733 , 0.96229, 1.0427 , 0.80152,
       0.91636, 0.98526, 0.66373, 0.57186, 0.64076, 0.60631])

In [62]:
df.dtypes

Time            float64
Frontal_Acc     float64
Vertical_Acc    float64
Lateral_Acc     float64
ID                int64
RSSI            float64
Phase           float64
 Frequency      float64
Activity          int64
dtype: object

In [23]:
df

Time  Frontal_Acc  Vertical_Acc  Lateral_Acc  ID  RSSI   Phase  \
0      0.00      0.11960       0.93932     0.043332   3 -61.0  5.3014   
1      2.75      0.41273       1.01970    -0.025087   3 -66.0  0.8805   
2      3.00      0.41273       1.01970    -0.025087   2 -59.5  4.4455   
3      3.50      0.52999       0.90487    -0.047893   3 -59.5  5.8583   
4      4.00      0.56517       0.74411    -0.447000   3 -61.5  5.4886   
..      ...          ...           ...          ...  ..   ...     ...   
173  444.00      0.90520       0.64076    -0.082102   1 -59.5  1.9574   
174  449.00      0.90520       0.64076    -0.082102   1 -59.0  6.2540   
175  451.50      0.42446       0.91636    -0.161920   1 -53.0  5.7156   
176  451.58      0.42446       0.91636    -0.161920   1 -52.0  5.8982   
177  452.25      0.58862       0.87042    -0.082102   1 -60.0  5.7033   

      Frequency  Activity  
0        922.25         1  
1        922.75         1  
2        923.75         1  
3        921.75         1  
4        923.25         1  
..          ...       ...  
173      922.25         2  
174      922.25         2  
175      922.25         4  
176      922.25         4  
177      925.75         4  

[178 rows x 9 columns]

In [24]:
x = df[['Frontal_Acc']]

In [25]:
x

Frontal_Acc
0        0.11960
1        0.41273
2        0.41273
3        0.52999
4        0.56517
..           ...
173      0.90520
174      0.90520
175      0.42446
176      0.42446
177      0.58862

[178 rows x 1 columns]

In [26]:
y = df[["Activity"]]

In [27]:
y

Activity
0           1
1           1
2           1
3           1
4           1
..        ...
173         2
174         2
175         4
176         4
177         4

[178 rows x 1 columns]

In [28]:
## Performing the linear regression

from sklearn.linear_model import LinearRegression

ml_model = LinearRegression()

In [29]:
ml_model.fit(x,y)

LinearRegression()

In [30]:
## Now finding the intercept

ml_model.intercept_

array([2.68494872])

In [32]:
ml_model.coef_

array([[-0.62608994]])